### ISSUE TITLE
Can't find file I/O subroutines in Fortran library (snopt7_python.so: undefined symbol: snfileclose_, snfileopenappend_, snfileopenread_)) 

### ISSUE THREAD

**Issue by skragelund** [snopt/snopt-python#7]
Hello,

This python interface has been very helpful. I have had the same issues as @HuaweiWang in #5 while using the snopt-only branch. Namely, my compiled SNOPT library does not contain snfileclose, snfileopenread, or snfileopenappend. I have been able to run SNOPT after commenting out these function calls in snopt7_python.f90, but this is quite hack-ey and prevents my code from reading .spc files or writing the results to anything but the screen. I have compiled SNOPT version 7.5-1.4 from source, and can run the included example problems without any issues. Likewise, I can run all snopt-python examples except snmainb (which fails while trying to read the specs file).

Any suggestions would be greatly appreciated!

**Comment by gnowzil** [comment]
I just added the file with those routines in the `util` directory.  Since you have source just pop it into `$SNOPT/src`.  You'll have to modify the `$SNOPT/src/Submakefile` by adding `snfilewrapper` to the list of files for `SNOPT`.  Let me know if this doesn't work.

**Comment by skragelund** [comment]
Thank you, that did the trick!
Much appreciated.
