### ISSUE TITLE
Dose python interface requires you to have both SNOPT and DNOPT ?

### ISSUE THREAD

**Issue by kurosh-z** [snopt/snopt-python#8]
I downloded the precompiled SNOPT files and copied to $HOME/lib as it described in instruction , 
here is where the files are  : 
![image](https://user-images.githubusercontent.com/32224317/45701584-f02c5000-bb6f-11e8-841e-4e08f0a76a62.png)
 and here is how my .zschrc looks like (equivalent to .bashrc) : 
![image](https://user-images.githubusercontent.com/32224317/45701690-2b2e8380-bb70-11e8-9199-2132a59519f3.png)
I still cannnot setup the Interface : 
`~/software/snopt-python(master*) » python setup.py build                                          kurosh@Kurosh-surface
Appending optimize.solvers configuration to optimize
Ignoring attempt to set 'name' (from 'optimize' to 'optimize.solvers')
Appending optimize.solvers/snopt configuration to optimize
Ignoring attempt to set 'name' (from 'optimize' to 'optimize.solvers/snopt')
Appending optimize.solvers/dnopt configuration to optimize
Ignoring attempt to set 'name' (from 'optimize' to 'optimize.solvers/dnopt')
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "optimize.solvers.snopt7_python" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py' to include_dirs.
building extension "optimize.solvers.dnopt_python" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py' to include_dirs.
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'optimize.solvers.dnopt_python' extension
compiling C sources
C compiler: gcc -pthread -B /home/kurosh/software/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py -I/home/kurosh/software/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/kurosh/software/anaconda3/include/python3.6m -c'
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
compile options: '-Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py -I/home/kurosh/software/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/kurosh/software/anaconda3/include/python3.6m -c'
gfortran:f90: solvers/f2py/dnopt_python.f90
solvers/f2py/dnopt_python.f90:386:22:

                     cu, lencu, iu, leniu, ru, lenru)
                      1
Warning: Unused dummy argument ‘cu’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:385:47:

 subroutine dummycon(mode, mNCon, nnJac, x, fCon, JCon, ldJ, Status, &
                                               1
Warning: Unused dummy argument ‘fcon’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:386:33:

                     cu, lencu, iu, leniu, ru, lenru)
                                 1
Warning: Unused dummy argument ‘iu’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:385:53:

 subroutine dummycon(mode, mNCon, nnJac, x, fCon, JCon, ldJ, Status, &
                                                     1
Warning: Unused dummy argument ‘jcon’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:385:24:

 subroutine dummycon(mode, mNCon, nnJac, x, fCon, JCon, ldJ, Status, &
                        1
Warning: Unused dummy argument ‘mode’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:386:44:

                     cu, lencu, iu, leniu, ru, lenru)
                                            1
Warning: Unused dummy argument ‘ru’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:385:66:

 subroutine dummycon(mode, mNCon, nnJac, x, fCon, JCon, ldJ, Status, &
                                                                  1
Warning: Unused dummy argument ‘status’ at (1) [-Wunused-dummy-argument]
solvers/f2py/dnopt_python.f90:385:41:

 subroutine dummycon(mode, mNCon, nnJac, x, fCon, JCon, ldJ, Status, &
                                         1
Warning: Unused dummy argument ‘x’ at (1) [-Wunused-dummy-argument]
/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py/dnopt_pythonmodule.o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py/fortranobject.o build/temp.linux-x86_64-3.6/solvers/f2py/dnopt_python.o -L/home/kurosh/software/lib -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -ldnopt -lgfortran -o build/lib.linux-x86_64-3.6/optimize/solvers/dnopt_python.cpython-36m-x86_64-linux-gnu.so
/usr/bin/x86_64-linux-gnu-ld: cannot find -ldnopt
collect2: error: ld returned 1 exit status
/usr/bin/x86_64-linux-gnu-ld: cannot find -ldnopt
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py/dnopt_pythonmodule.o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/solvers/f2py/fortranobject.o build/temp.linux-x86_64-3.6/solvers/f2py/dnopt_python.o -L/home/kurosh/software/lib -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -ldnopt -lgfortran -o build/lib.linux-x86_64-3.6/optimize/solvers/dnopt_python.cpython-36m-x86_64-linux-gnu.so" failed with exit status 1`

**Comment by gnowzil** [comment]
Use branch `snopt-only`.
